# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-27 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170826_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': '\u56fd\u5bb6\u4fe1\u606f', 'verbose_name_plural': '\u56fd\u5bb6\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': '\u7701\u4efd\u4fe1\u606f', 'verbose_name_plural': '\u7701\u4efd\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='trade',
            options={'verbose_name': '\u884c\u4e1a\u4fe1\u606f', 'verbose_name_plural': '\u884c\u4e1a\u4fe1\u606f'},
        ),
    ]
