# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-27 16:35
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_or_update', models.CharField(choices=[('new', '\u65b0\u5efa'), ('update', '\u4fee\u6539')], default='new', max_length=6, verbose_name='\u7f16\u8f91\u7c7b\u578b')),
                ('article_title', models.CharField(default='\u65b0\u6587\u7ae0', max_length=100, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('article_image', models.ImageField(null=True, upload_to='images/facephoto', verbose_name='\u5c01\u9762\u56fe')),
                ('pub_time', models.DateField(default=datetime.datetime.now, verbose_name='\u53d1\u5e03\u65e5\u671f')),
                ('content', DjangoUeditor.models.UEditorField(verbose_name='\u6587\u7ae0\u5185\u5bb9')),
                ('fav_count', models.IntegerField(default=0, verbose_name='\u70b9\u8d5e\u6570\u91cf')),
                ('com_count', models.IntegerField(default=0, verbose_name='\u8bc4\u8bba\u6570\u91cf')),
                ('url', models.URLField(default='http://tbt.cjluzzl.cn/article/1/1.html', verbose_name='\u6587\u7ae0\u94fe\u63a5')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0\u8be6\u60c5',
                'verbose_name_plural': '\u6587\u7ae0\u8be6\u60c5',
            },
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_or_update', models.CharField(choices=[('new', '\u65b0\u5efa'), ('update', '\u4fee\u6539')], default='new', max_length=6, verbose_name='\u7f16\u8f91\u7c7b\u578b')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u8bc4\u8bba\u65f6\u95f4')),
                ('content', models.CharField(max_length=200, verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article', verbose_name='\u6240\u8bc4\u6587\u7ae0')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8bc4\u8bba\u4eba')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0\u8be6\u60c5',
                'verbose_name_plural': '\u6587\u7ae0\u8be6\u60c5',
            },
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default='\u56fd\u5185\u65b0\u95fb', max_length=20, verbose_name='\u6587\u7ae0\u7c7b\u578b')),
                ('count', models.IntegerField(default=0, verbose_name='\u6587\u7ae0\u6570\u91cf')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0\u7c7b\u578b',
                'verbose_name_plural': '\u6587\u7ae0\u7c7b\u578b',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType', verbose_name='\u6587\u7ae0\u7c7b\u578b'),
        ),
    ]
