# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-27 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': '\u6587\u7ae0\u8bc4\u8bba', 'verbose_name_plural': '\u6587\u7ae0\u8bc4\u8bba'},
        ),
    ]
