# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-02 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20170827_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read_num',
            field=models.IntegerField(default=0, verbose_name='\u6d4f\u89c8\u91cf'),
        ),
    ]
