# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-28 18:00
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sps_num', models.CharField(max_length=100, verbose_name='\u901a\u62a5\u53f7')),
                ('ics_num', models.CharField(max_length=100, verbose_name='ICS\u53f7')),
                ('pub_time', models.DateField(default=datetime.datetime.now, verbose_name='\u53d1\u5e03\u65e5\u671f')),
                ('end_time', models.DateField(default=datetime.datetime.now, verbose_name='\u622a\u6b62\u65e5\u671f')),
                ('tbt_member', models.CharField(default='\u8bf7\u8f93\u5165\u6210\u5458\u540d', max_length=100, verbose_name='\u901a\u62a5\u6210\u5458')),
                ('aim', models.CharField(default='\u4fdd\u62a4\u73af\u5883', max_length=100, verbose_name='\u76ee\u6807\u548c\u7406\u7531')),
                ('short_content', models.CharField(max_length=200, verbose_name='\u5185\u5bb9\u6982\u8ff0')),
                ('content', DjangoUeditor.models.UEditorField(verbose_name='\u6b63\u6587')),
            ],
            options={
                'verbose_name': 'WTO/SPS\u901a\u62a5',
                'verbose_name_plural': 'WTO/SPS\u901a\u62a5',
            },
        ),
        migrations.CreateModel(
            name='Tbt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbt_num', models.CharField(max_length=100, verbose_name='\u901a\u62a5\u53f7')),
                ('ics_num', models.CharField(max_length=100, verbose_name='ICS\u53f7')),
                ('pub_time', models.DateField(default=datetime.datetime.now, verbose_name='\u53d1\u5e03\u65e5\u671f')),
                ('end_time', models.DateField(default=datetime.datetime.now, verbose_name='\u622a\u6b62\u65e5\u671f')),
                ('tbt_member', models.CharField(default='\u8bf7\u8f93\u5165\u6210\u5458\u540d', max_length=100, verbose_name='\u901a\u62a5\u6210\u5458')),
                ('aim', models.CharField(default='\u4fdd\u62a4\u73af\u5883', max_length=100, verbose_name='\u76ee\u6807\u548c\u7406\u7531')),
                ('short_content', models.CharField(max_length=300, verbose_name='\u5185\u5bb9\u6982\u8ff0')),
                ('content', DjangoUeditor.models.UEditorField(verbose_name='\u6b63\u6587')),
            ],
            options={
                'verbose_name': 'WTO/TBT\u901a\u62a5',
                'verbose_name_plural': 'WTO/TBT\u901a\u62a5',
            },
        ),
    ]
