# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-02 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170827_1634'),
        ('tbtsps', '0002_auto_20170828_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbt',
            name='tbt_trad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Trade', verbose_name='\u6240\u5c5e\u884c\u4e1a'),
        ),
    ]
