# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-02 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbtsps', '0004_sps_sps_trad'),
    ]

    operations = [
        migrations.AddField(
            model_name='sps',
            name='read_num',
            field=models.IntegerField(default=0, verbose_name='\u6d4f\u89c8\u91cf'),
        ),
        migrations.AddField(
            model_name='tbt',
            name='read_num',
            field=models.IntegerField(default=0, verbose_name='\u6d4f\u89c8\u91cf'),
        ),
    ]
